receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 128

extensions:
  health_check: {}
  memory_ballast:
    size_mib: 64
  zpages:
    endpoint: 127.0.0.1:55679
exporters:
  # zipkin:
  #   endpoint: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"
  # otlphttp:
  #   endpoint: "http://otel-collector-ext:4318"
  #   tls:
  #     insecure: true  
  prometheus:
    endpoint: "0.0.0.0:8890"
    resource_to_telemetry_conversion:
      enabled: true
  logging: {}
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
service:
  extensions: [health_check, memory_ballast, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
