[package]
edition = "2021"
name = "bitski-eip-712"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
num = "0.4"
regex = "1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = {version = "2.0", default-features = false}
web3 = "0.17"
